### PR TITLE
Implementation of ZText (SDF-based fonts) and overlay handling in RendeQuTor

### PR DESCRIPTION
**Pull request by osschar**
See examples/textExampleSDF/main.js

Contains contributions from Waad, Alja and Matevz. Squashed to avoid adding of extra font files in the repo (and avoid 18 commits).
- Waad: initial implementation & tuning.
- Alja: integration with REve.
- Matevz: final cleanup, loading of fonts & font metrics.

Full set of commits available in https://github.com/alja/RenderCore/tree/master-dec24-1450

For font generation use this (see mk_fonts.sh, gzip -9 the json font-metrics).
https://github.com/osschar/sdf_atlas

### CODE REVIEW

**Comment by alja** [comment]
@ss4774 I'm currently testing integration to REve.

**Comment by ss4774** [comment]
I like the results! Let me know when the code will be ready for a merge.

**Comment by osschar** [comment]
Screenshot from 2024-06-03 23-42-50

**Comment by osschar** [comment]
Yes, almost there :)

**Comment by osschar** [comment]
Screenshot from 2024-06-06 23-10-42
This is how it looks in REve demo with the latest commit ... added support for backpanel and frame.
I think I'm getting close ... have tons of ideas now but there are also other things I have to get back to :)

**Comment by osschar** [comment]
This is ready to go ... we might have some more things later, like implementation of mixed mode: position in world-coordinates, size in screen units.

**Comment by ss4774** [comment]
Merging the pull request.

**Pull request merged**
